export const CATEGORIES = [
  {
    id: "stickers",
    label: "Stickers",
    icon: "sticker",
    items: [
      { name: "Custom Sticker (1 piece)", price: 15, image: "/products/custom-sticker.png", slug: "custom-sticker", isCustom: true },
      { name: "Jiraya Sticker", price: 12,image:"/products/Jiraya.jpeg",slug: "jiraya-sticker", inStock: true },
      { name: "Itachi Sticker", price: 12,image:"/products/Itachi.jpeg",slug: "itachi-sticker",inStock: true },
      { name: "Itachi Uchiha Sticker", price: 12,image:"/products/Itachi-Uchiha.jpeg",slug: "itachi-uchiha-sticker",inStock: true },
      { name: "Kakashi Hatake Sticker", price: 12,image:"/products/Kakashi-Hatake.jpeg",slug: "kakashi-hatake-sticker",inStock: true },
      { name: "Sukuna Peeker Sticker", price: 12,image:"/products/anime_s.jpeg",slug: "sukuna-peeker-sticker",inStock: true },
      { name: "Porsche 911 Sticker", price: 12,image:"/products/porsche_911.jpeg",slug: "porsche-sticker",inStock: true },
      { name: "Floral Skull Sticker", price: 12,image:"/products/floral_skull.jpeg",slug: "floral-skull-sticker",inStock: true },
      { name: "Batman Sticker", price: 12,image:"/products/batman.jpeg",slug: "batman-sticker",inStock: true },
      { name: "Coffee Drip Sticker", price: 12,image:"/products/coffee-drip.jpeg",slug: "coffee-drip-sticker",inStock: true },
      { name: "Maomao Sticker", price: 12,image:"/products/girl.jpeg",slug: "maomao-sticker",inStock: true },
      { name: "Iced Coffee Girly Sticker", price: 12,image:"/products/iced-coffee.jpeg",slug: "iced-coffee-girly-sticker",inStock: true },
      { name: "Mood Alert Sticker", price: 12,image:"/products/not-in-mood.jpeg",slug: "mood-alert-sticker",inStock: true },
      { name: "Espresso Patronum Sticker", price: 12,image:"/products/espresso.jpeg",slug: "espresso-patronum-sticker",inStock: true },
      { name: "Book Pill Sticker", price: 12,image:"/products/book-pill.jpeg",slug: "book-pill-sticker",inStock: true },
      { name: "No Prob-llama Sticker", price: 12,image:"/products/prob-lama.jpeg",slug: "no-prob-llama-sticker",inStock: true },
      { name: "Time To Recharge Sticker", price: 12,image:"/products/recharge.jpeg",slug: "time-to-recharge-sticker",inStock: true },
      { name: "Error 404 Sticker", price: 12,image:"/products/error-404.jpeg",slug: "error-404-sticker",inStock: true },
      { name: "Itachi Crimson Moon & Crows Sticker", price: 12,image:"/products/itachi-crimson.jpeg",slug: "itachi-crimson-moon&crows-sticker",inStock: true },
      { name: "Drink More Water Sticker", price: 12,image:"/products/water.jpeg",slug: "drink-more-water-sticker",inStock: true },
      { name: "Anything is Possible Sticker", price: 12,image:"/products/possible.jpeg",slug: "anything-is-possible-sticker",inStock: true },
      { name: "Supra Sticker", price: 12,image:"/products/Supra.jpeg",slug: "supra-sticker",inStock: true },
      { name: "Kehndi Hundi C Sticker", price: 12,image:"/products/kehndi.jpeg",slug: "kehndi-hundiC-sticker",inStock: true },
      { name: "Quad Aces Sticker", price: 12,image:"/products/aces.jpeg",slug: "quad-aces-sticker",inStock: true },
      { name: "Under Control Sticker", price: 12,image:"/products/under-control.jpeg",slug: "under-control-sticker",inStock: true },
      { name: "I am Sweet Enough Sticker", price: 12,image:"/products/sweet.jpeg",slug: "i-am-sweet-enough-sticker",inStock: true },
      { name: "Among Us Sticker", price: 12,image:"/products/amongus.jpeg",slug: "among-us-sticker",inStock: true },
      { name: "Be Kind Sticker", price: 12,image:"/products/bekind.jpeg",slug: "be-kind-sticker",inStock: true },
      { name: "Pink Hearts Sticker", price: 12,image:"/products/hearts.jpeg",slug: "pink-hearts-sticker",inStock: true },
      { name: "Diet Coke Addiction Sticker", price: 12,image:"/products/dietcoke.jpeg",slug: "dietcoke-addiction-sticker",inStock: true },
      { name: "Diet Coke Cigs Sticker", price: 12,image:"/products/dietcokecigs.jpeg",slug: "dietcoke-cigs-sticker",inStock: true },
      { name: "Professor Frog Sticker", price: 12,image:"/products/frog.jpeg",slug: "professor-frog-sticker",inStock: true },
      { name: "Simpsons Sticker", price: 12,image:"/products/lisa.jpeg",slug: "simpsons-sticker",inStock: true },
      { name: "Spiderman Sticker", price: 12,image:"/products/spiderman.jpeg",slug: "spiderman-sticker",inStock: true },
      { name: "Mr.Bean Sticker", price: 12,image:"/products/bean.jpeg",slug: "mrbean-sticker",inStock: true },
      { name: "Netflix $ Child Sticker", price: 12,image:"/products/chill.jpeg",slug: "netflix&chill-sticker",inStock: true },
      { name: "Chai is Life Sticker", price: 12,image:"/products/chai.jpeg",slug: "chai-is-life-sticker",inStock: true },
      { name: "Idiot Repellent Sticker", price: 12,image:"/products/idiot.jpeg",slug: "idiot-repellent-sticker",inStock: true },
      { name: "I Decline to Socialize Sticker", price: 12,image:"/products/socialize.jpeg",slug: "i-decline-to-socialize-sticker",inStock: true },
      { name: "Froget About It Sticker", price: 12,image:"/products/froget.jpeg",slug: "froget-about-it-sticker",inStock: true },
      { name: "None Of My Business Sticker", price: 12,image:"/products/business.jpeg",slug: "none-of-my-business-sticker",inStock: true },
      { name: "Frog Meme Sticker", price: 12,image:"/products/frogmeme.jpeg",slug: "frog-meme-sticker",inStock: true },
      { name: "Michael Scott Meme Sticker", price: 12,image:"/products/scott.jpeg",slug: "michael-scott-meme-sticker",inStock: true },
      { name: "Overthinkers Club Sticker", price: 12,image:"/products/overthinkers.jpeg",slug: "overthinkers-club-sticker",inStock: true },
      { name: "Social Battery Sticker", price: 12,image:"/products/socialbattery.jpeg",slug: "social-battery-sticker",inStock: true },
      { name: "Anatomical Heart Sticker", price: 12,image:"/products/anatomicalheart.jpeg",slug: "anatomical-heart-sticker",inStock: true },
      { name: "Karma Uno Reverse Sticker", price: 12,image:"/products/karmauno.jpeg",slug: "karma-uno-reverse-sticker",inStock: true },
      { name: "11:11 Sticker", price: 12,image:"/products/wish.jpeg",slug: "11-11-sticker",inStock: true },
      { name: "Flower Bouquet Sticker", price: 12,image:"/products/flowerbouquet.jpeg",slug: "flower-bouquet-sticker",inStock: true },
      { name: "Yellow Butterfly Sticker", price: 12,image:"/products/yellowbutterfly.jpeg",slug: "yellow-butterfly-sticker",inStock: true },
      { name: "Pink Butterfly Sticker", price: 12,image:"/products/pinkbutterfly.jpeg",slug: "pink-butterfly-sticker",inStock: true },
      { name: "Blue Butterfly Sticker", price: 12,image:"/products/bluebutterfly.jpeg",slug: "blue-butterfly-sticker",inStock: true },
      { name: "+1000 Aura Sticker", price: 12,image:"/products/aura.jpeg",slug: "+1000-aura-sticker",inStock: true },
      { name: "Wasted Sticker", price: 12,image:"/products/wasted.jpeg",slug: "wasted-sticker",inStock: true },
      { name: "Tech Dog Sticker", price: 12,image:"/products/pochacco.jpeg",slug: "tech-dog-sticker",inStock: true },
      { name: "Shiba Inu Dog Sticker", price: 12,image:"/products/shiba-inu-dog.jpeg",slug: "shiba-inu-dog-sticker",inStock: true },
      { name: "Cozy Cat Sticker", price: 12,image:"/products/tabby-cat.jpeg",slug: "cozy-cat-sticker",inStock: true },
      { name: "Bookworm Cat Sticker", price: 12,image:"/products/orange-cat.jpeg",slug: "bookworm-cat-sticker",inStock: true },
      { name: "Cat Stack Sticker", price: 12,image:"/products/pile-cat.jpeg",slug: "cat-stack-sticker",inStock: true },
      { name: "Pizza Slice Sticker", price: 12,image:"/products/pizza.jpeg",slug: "pizza-slice-sticker",inStock: true },
      { name: "Pistachio Pancake Sticker", price: 12,image:"/products/pancake.jpeg",slug: "pistachio-pancake-sticker",inStock: true },
      { name: "Nutella Banana Bread Sticker", price: 12,image:"/products/bread.jpeg",slug: "nutella-banana-bread-sticker",inStock: true },
      { name: "Buldak Ramen Sticker", price: 12,image:"/products/samyang-carbonara.jpeg",slug: "buldak-ramen-sticker",inStock: true },
      { name: "Naruto Sticker", price: 12,image:"/products/naruto.jpeg",slug: "naruto-sticker",inStock: true },
      { name: "Good Vibes Sticker", price: 12,image:"/products/good-vibes.jpeg",slug: "good-vibes-sticker",inStock: true },
      { name: "Pink & Red Retro Heart Sticker", price: 12,image:"/products/red-heart.jpeg",slug: "pink-red-retro-heart-sticker",inStock: true },
      { name: "Pink Bloom Sticker", price: 12,image:"/products/pink-flower.jpeg",slug: "pink-bloom-sticker",inStock: true },
      { name: "Peach Bloom Sticker", price: 12,image:"/products/peach-bloom.jpeg",slug: "peach-bloom-sticker",inStock: true },
      { name: "Floral Sticker Stamp ", price: 55,image:"/products/stamp-set.jpeg",slug: "floral-sticker-stamp",inStock: true },
      { name: "Tokyo Stamp Sticker", price: 12,image:"/products/japan.jpeg",slug: "tokyo-stamp-sticker",inStock: true },
      { name: "Paris Stamp Sticker", price: 12,image:"/products/paris.jpeg",slug: "paris-stamp-sticker",inStock: true },
      { name: "Anxiety All Star Sticker", price: 12,image:"/products/anxiety_star.png",slug: "anxiety-all-star-sticker",inStock: true },
      { name: "Business Proposal Drama Sticker", price: 12,image:"/products/business_proposal.png",slug: "business-proposal-drama-sticker",inStock: true },
      { name: "Hot Mess Sticker", price: 12,image:"/products/hot_mess.png",slug: "hot-mess-sticker",inStock: true },
      { name: "Money Heist Professor Sticker", price: 12,image:"/products/money_heist.png",slug: "money-heist-professor-sticker",inStock: true },
      { name: "Stranger Things Sticker", price: 12,image:"/products/stranger_things.png",slug: "stranger-things-sticker",inStock: true },
      { name: "The Boys Sticker", price: 12,image:"/products/The_boys.png",slug: "the-boys-sticker",inStock: true },
      { name: "Work Mode On Sticker", price: 12,image:"/products/Work_mode_on.png",slug: "work-mode-on-sticker",inStock: true },
      { name: "Blossom Ride Sticker", price: 12,image:"/products/blossomride.jpeg",slug: "blossom-ride-sticker",inStock: true },
      { name: "FCB Sticker", price: 12,image:"/products/fcb.jpeg",slug: "fcb-sticker",inStock: true },
      { name: "Football On Fire Sticker", price: 12,image:"/products/footballfire.jpeg",slug: "football-on-fire-sticker",inStock: true },
      { name: "Grow Girl Plant Sticker", price: 12,image:"/products/growgirlplant.jpeg",slug: "grow-girl-plant-sticker",inStock: true },
      { name: "K-Drama & Chill Sticker", price: 12,image:"/products/kdrama.jpeg",slug: "k-drama-chill-sticker",inStock: true },
      { name: "Life Is About Goals Sticker", price: 12,image:"/products/lifegoals.jpeg",slug: "life-is-about-goals-sticker",inStock: true },
      { name: "Air Jet Sticker", price: 12,image:"/products/airjet.jpeg",slug: "air-jet-sticker",inStock: true },
      { name: "Biker Sticker", price: 12,image:"/products/biker.jpeg",slug: "biker-sticker",inStock: true },
      { name: "Tired College Student Sticker", price: 12,image:"/products/clg.jpeg",slug: "tired-college-student-sticker",inStock: true },
      { name: "Diva Energy Sticker", price: 12,image:"/products/diva.jpeg",slug: "diva-energy-sticker",inStock: true },
      { name: "Love You Sticker", price: 12,image:"/products/loveyou.jpeg",slug: "love-you-sticker",inStock: true },
      { name: "Men's Opinion Sticker", price: 12,image:"/products/opinion.jpeg",slug: "mens-opinion-sticker",inStock: true },
      { name: "Pav Bhaji Sticker", price: 12,image:"/products/pavbhaji.jpeg",slug: "pav-bhaji-sticker",inStock: true },
      { name: "Powerful Women Sticker", price: 12,image:"/products/powerful.jpeg",slug: "powerful-women-sticker",inStock: true },
      { name: "Sassy Sticker", price: 12,image:"/products/sassy.jpeg",slug: "sassy-sticker",inStock: true },
      { name: "Male Tears Sticker", price: 12,image:"/products/tears.jpeg",slug: "male-tears-sticker",inStock: true },
      { name: "Messi Sticker", price: 12,image:"/products/messi.jpeg",slug: "messi-sticker",inStock: true },
      { name: "Spider-Man Advanced Suit Sticker", price: 12,image:"/products/spiderman_s.jpeg",slug: "spiderman-advanced-suit-sticker",inStock: true },
      { name: "Stich Holding Scrump Sticker", price: 12,image:"/products/stich.jpeg",slug: "stich-holding-scrump-sticker",inStock: true },
    ],
  },
   {
    id: "stickerpack",
    label: "Sticker Pack",
    icon: "stickerpack",
    aspectRatio: "1 / 1",
    items: [
      // { name: "Custom Sticker Pack (1 piece)", price: 119, image: "/products/custom-sticker.png", isCustom: true },
      { name: "Panda Sticker Set (9pcs)", price: 89,images: ["/products/panda-pack-2.jpeg","/products/panda-pack.jpeg"],slug: "panda-sticker-set",inStock: true },
      { name: "Froggy Sticker Set (9pcs)", price: 89,images: ["/products/froggy-pack.jpeg","/products/froggy-pack-2.jpeg"],slug: "froggy-sticker-set",inStock: true },
      { name: "friends Sticker Set (6pcs)", price: 79,images: ["/products/friends-pack.jpeg","/products/friends-pack-2.jpeg"],slug: "friends-sticker-set",inStock: true },
    ],
  },
   {
    id: "miniposters",
    label: "Mini Poster Set",
    icon: "miniposter",
    aspectRatio: "4 / 5",
    items: [
      { name: "Custom Poster (1 piece)", price: 50, image: "/products/custom-sticker.png", slug: "custom-poster",isCustom: true },
      { name: "Retro Desi Pop Poster Set", price: 179,image:"/products/desi_poster.jpeg",slug: "retro-desi-pop-poster-set",inStock: true },
      { name: "Classic Spiderman Poster Set", price: 179,image:"/products/spiderman-poster.jpeg",slug: "classic-spiderman-poster-set",inStock: true },
      { name: "Growth Mindset Poster Set", price: 179,image:"/products/growth_poster.jpeg",slug: "growth-mindset-poster-set",inStock: true },
      { name: "Sweet & Spicy Poster Set", price: 179,image:"/products/heart_poster.jpeg",slug: "sweet-spicy-poster-set",inStock: true },
      { name: "Retro Rhythm Poster Set", price: 179,image:"/products/retro-poster.jpeg",slug: "retro-rhythm-poster-set",inStock: true },
      { name: "The Caffeine Club Set", price: 179,image:"/products/caffeine_poster.jpeg",slug: "the-caffeine-club-set",inStock: true },
    ],
  },
   {
    id: "bigposters",
    label: "Big Wall Posters",
    icon: "bigposter",
    aspectRatio: "3 / 4",
    items: [
      { name: "Custom Poster (1 piece)", price: 119, image: "/products/custom-sticker.png", slug: "custom-poster", isCustom: true },
      { name: "Keep Flying Poster (12x18)", price: 99,image:"/products/flying.jpeg",slug: "keep-flying-poster",inStock: true },
      { name: "Like Jennie Poster (12x18)", price: 99,image:"/products/jennie_p.jpeg",slug: "likejennie-poster",inStock: true },
      { name: "Virat Kohli Poster (12x18)", price: 99,image:"/products/kohli_p.jpeg",slug: "viratkohli-poster",inStock: true },
    ],
  },
   {
    id: "frame",
    label: "Wall Frames",
    icon: "frame",
    aspectRatio: "3 / 4",
    items: [
      { name: "Custom Wall Frame (1 piece)", price: 419, image: "/products/custom-sticker.png", slug: "custom-wall-frame", isCustom: true },
      { name: "M.S Dhoni Wall Frame (12x18)", price: 399,image:"/products/dhoni_f.png",slug: "msdhoni-wall-frame",inStock: true },
      { name: "Virat Kohli Wall Frame (12x18)", price: 399,image:"/products/virat_f.png",slug: "viratkohli-wall-frame",inStock: true },
      { name: "Virat Kohli Believe Wall Frame (12x18)", price: 399,image:"/products/kohli_f.png",slug: "viratkohli-believe-wall-frame",inStock: true },
      { name: "Keep Flying Wall Frame (12x18)", price: 399,image:"/products/flying_f.jpeg",slug: "keep-flying-wall-frame",inStock: true },
      { name: "Like Jennie Wall Frame (12x18)", price: 399,image:"/products/jennie_f.jpeg",slug: "likejennie-wall-frame",inStock: true },
    ],
  },
   {
    id: "bookmarks",
    label: "Bookmarks",
    icon: "bookmark",
    aspectRatio: "4 / 5",
    items: [
      { name: "Starry Night Bookmark", price: 49,image:"/products/starry-night.jpeg",slug: "starry-night-bookmark", inStock: true},
      { name: "Starry Night Over The River Bookmark", price: 49,image:"/products/starry-night-river.jpeg",slug: "starry-night-over-the-river-bookmark", inStock: true },
      { name: "Cozy Book Nook Bookmark", price: 49,image:"/products/cozy-book.jpeg",slug: "cozy-book-nook-bookmark", inStock: true},
      { name: "Zenitsu Agatsuma Bookmark", price: 49,image:"/products/yellow_bk.jpeg",slug: "zenitsu-agatsuma-bookmark", inStock: true},
      { name: "Nezuko Kamado Bookmark", price: 49,image:"/products/pink_bk.jpeg",slug: "nezuko-kamado-bookmark", inStock: true},
      { name: "Tanjiro Kamado Bookmark", price: 49,image:"/products/green_bk.jpeg",slug: "tanjiro-kamado-bookmark", inStock: true},
      { name: "Mountain Trail Bookmark", price: 49,image:"/products/mountain_bm_final.jpeg",slug: "mountain-trail-bookmark", inStock: true},
      { name: "Midnight Sakura Glow Bookmark", price: 49,image:"/products/midnight_bm_final.jpeg",slug: "midnight-sakura-glow-bookmark", inStock: true},
      { name: "Japanese Landscape Bookmark", price: 49,image:"/products/japan_bm_finall.jpeg",slug: "japanese-landscape-bookmark", inStock: true},
      { name: "Tokyo Twilight Bookmark", price: 49,image:"/products/tokyo_bm_finall.jpeg",slug: "tokyo-twilight-bookmark", inStock: true},
      { name: "Ink & Lemonade Bookmark", price: 49,image:"/products/ink_bm_final.jpeg",slug: "ink-and-lemonade-bookmark", inStock: true},
      { name: "Keep Reading Bookmark", price: 49,image:"/products/reading_bm.jpeg",slug: "keep-reading-bookmark", inStock: true},
      { name: "You Are On This Page Bookmark", price: 49,image:"/products/page_bm.jpeg",slug: "you-are-on-this-page-bookmark", inStock: true},
      { name: "Sushi Platter Bookmark", price: 55,image:"/products/sushi.jpeg",slug: "sushi-platter-bookmark", inStock: true},
      { name: "Reading Fuel Bookmark", price: 49,image:"/products/fuel.jpeg",slug: "reading-fuel-bookmark", inStock: true},


    ],
  },
  {
    id: "memopads",
    label: "Memo Pads",
    icon: "pad",
    items: [
      { name: "Pastel Peach Rabbit Memo Pad", price: 59,image:"/products/peach.jpeg",slug: "pastel-peach-rabbit-memo-pad", inStock: true },
      { name: "Pastel Pink Rabbit Memo Pad", price: 59,image:"/products/pink.jpeg",slug: "pastel-pink-rabbit-memo-pad", inStock: true },
      { name: "Pastel Blue Rabbit Memo Pad", price: 59,image:"/products/blue.jpeg",slug: "pastel-blue-rabbit-memo-pad", inStock: true },
      { name: "Pastel Yellow Rabbit Memo Pad", price: 59,image:"/products/yellow.jpeg",slug: "pastel-yellow-rabbit-memo-pad", inStock: true },
      { name: "Lazy Cat Memo Pad", price: 79,image:"/products/lazy-cat.jpeg",slug: "lazy-cat-memo-pad", inStock: true },
      { name: "Smart Cat Lined Memo Pad", price: 79,image:"/products/smart-cat.jpeg",slug: "smart-cat-lined-memo-pad", inStock: true },
      { name: "Shiba Inu Kawaii Memo Pad", price: 79,image:"/products/shiba-inu.jpeg",slug: "shiba-inu-kawaii-memo-pad", inStock: true },
      { name: "Blue Bear Grid Memo Pad", price: 79,image:"/products/blue-bear.jpeg",slug: "blue-bear-grid-memo-pad", inStock: true },
    ],
  },
  {
    id: "notebook",
    label: "Journals & Notepads",
    icon: "notebook",
    items: [
      // { name: "Creamy Avacado Notebook", price: 119,image:"/products/avacado.png",inStock: true },
      // { name: "Plump Grape Notebook", price: 119,image:"/products/grapes.png",inStock: true },
      // { name: "Cheerful Cherry Notebook", price: 119,image:"/products/cherry.png",inStock: true },
      // { name: "Pastel Peach Notebook", price: 119,image:"/products/peach.png",inStock: true },
      // { name: "Fresh Strawberry Notebook", price: 119,image:"/products/strawberry.png",inStock: true },
      { name: "Death Note Journal", price: 119,image:"/products/death-note.png",slug: "death-note-journal",inStock: true },
      { name: "Be Positive Journal", price: 119,image:"/products/Be-positive.png",slug: "be-positive-journal",inStock: true },
      { name: "Believe In Yourself Journal", price: 119,image:"/products/believe-in.png",slug: "believe-in yourself-journal",inStock: true },
      { name: "Y2K Heartwave Journal", price: 119,image:"/products/heartwave.png",slug: "y2k-heartwave-journal",inStock: true },
      { name: "You Can Do It Journal", price: 119,image:"/products/you-can.png",slug: "you-can-do-it-journal",inStock: true },
      { name: "Sunflower and Bee Journal", price: 119,image:"/products/Sunflower_nb.png",slug: "sunflower-and-bee-journal",inStock: true },
      { name: "Pink Bow Floral Journal", price: 119,image:"/products/Pinkbow_nb.png",slug: "pink-bow-floral-journal",inStock: true },
      { name: "Peaceful Pink Spiral Notepad", price: 99,image:"/products/peace_np.png",slug: "peaceful-pink-spiral-notepad",inStock: true },
      { name: "Mint Bloom Plant Spiral Notepad", price: 99,image:"/products/bloom_np.png",slug: "mint-bloom-plant-spiral-notepad",inStock: true },
      { name: "Hug Me Cactus Spiral Notepad", price: 99,image:"/products/hugme_np.png",slug: "hug-me-cactus-spiral-notepad",inStock: true },
      { name: "Grow Plant Spiral Notepad ", price: 99,image:"/products/grow_np.png",slug: "grow-plant-spiral-notepad",inStock: true },
    ],
  },
    {
    id: "sticky",
    label: "Sticky Notes",
    icon: "sticky",
    aspectRatio: "4 / 3",
    items: [
      { name: "Pink Transparent Sticky Note", price: 79,image:"/products/pink_sn.png",slug: "pink-transparent-sticky-note",inStock: true },
      { name: "Purple Transparent Sticky Note", price: 79,image:"/products/purple_sn.png",slug: "purple-transparent-sticky-note",inStock: true },
      { name: "Yellow Transparent Sticky Note", price: 79,image:"/products/yellow_sn.png",slug: "yellow-transparent-sticky-note",inStock: true },
      { name: "Blue Transparent Sticky Note", price: 79,image:"/products/blue_sn.png",slug: "blue-transparent-sticky-note",inStock: true },
      { name: "Snow Fluff Sticky Note", price: 99,image:"/products/Snow_Fluff.png",slug: "snow-fluff-sticky-note",inStock: true },
      { name: "Star Nibble Sticky Note", price: 99,image:"/products/Star_Nibble.png",slug: "star-nibble-sticky-note",inStock: true },
      { name: "Hug Brew Sticky Note", price: 99,image:"/products/Hug_Brew.png",slug: "hug-brew-sticky-note",inStock: true },
      { name: "Sweet Hop Sticky Note", price: 99,image:"/products/Sweet_Hop.png",slug: "sweet-hop-sticky-note",inStock: true },
    ],
  },
    {
    id: "washi",
    label: "Washi Tapes",
    icon: "tape",
    aspectRatio: "3 / 2",
    items: [
      { name: "Floral Pink Heart Washi Tape", price: 180,image:"/products/pinkwashi.png",
        hasVariants: true,
      variants: [
        { label: "Single roll (1 piece)", price: 20 },
        { label: "Five roll (5 pcs)", price: 90 },
        { label: "Full set (10 pcs)", price: 180 },
      ],
      slug: "floral-pink-heart-washi-tape",
        inStock: true },
      { name: "Black and Gold Foil Washi Tape", price: 180,image:"/products/blackwashi.png", 
        hasVariants: true,
      variants: [
        { label: "Single roll (1 piece)", price: 20 },
        { label: "Five roll (5 pcs)", price: 90 },
        { label: "Full set (10 pcs)", price: 180 },
      ],
      slug: "black-and-gold-foil-washi-tape",
        inStock: true },
    ],
  },
  {
    id: "erasers",
    label: "Erasers",
    icon: "eraser",
    items: [
      { name: "Tropical Eraser Set", price: 60,image:"/products/tropical.jpeg",slug: "tropical-eraser-set",inStock: true },
      { name: "Rainbow Eraser Set", price: 60,image:"/products/rainbow.jpeg",slug: "rainbow-eraser-set",inStock: true },
      { name: "Chocolate Bar Eraser", price: 65,image:"/products/choco-eraser.png",slug: "chocolate-bar-eraser",inStock: true },
    ],
  }
];